parameters:
    sakiro_converter.provider.google.class: Sakiro\ConverterBundle\Provider\GoogleRateProvider
    sakiro_converter.provider.chain.class: Sakiro\ConverterBundle\Provider\ChainRateProvider
    sakiro_converter.provider.yahoo.class: Sakiro\ConverterBundle\Provider\YahooRateProvider
    sakiro_converter.provider.currency_api.class: Sakiro\ConverterBundle\Provider\CurrencyApiRateProvider

services:
    sakiro_converter.convert:
        class: Sakiro\ConverterBundle\Service\Convert
        arguments: [@sakiro_converter.provider.default]
