parameters:
    morbicer_converter.provider.google.class: Morbicer\ConverterBundle\Provider\GoogleRateProvider
    morbicer_converter.provider.chain.class: Morbicer\ConverterBundle\Provider\ChainRateProvider
    morbicer_converter.provider.yahoo.class: Morbicer\ConverterBundle\Provider\YahooRateProvider
    morbicer_converter.provider.currency_api.class: Morbicer\ConverterBundle\Provider\CurrencyApiRateProvider

services:
    morbicer_converter.convert:
        class: Morbicer\ConverterBundle\Service\Convert
        arguments: [@morbicer_converter.provider.default]
